export const styles = `
.dsh-drawing-tool-row{display:flex;align-items:center;gap:9px;min-height:30px;padding:2px 0;color:var(--dsw-alias-label-secondary,#60666e);font:13px/1.4 ui-rounded,"PingFang SC",sans-serif}
.dsh-drawing-tool-mark{width:10px;height:10px;border:2px solid #0c5568;border-radius:3px;background:linear-gradient(135deg,#f6bd60 0 48%,#46b7b2 49%);box-shadow:0 0 0 3px color-mix(in srgb,#46b7b2 15%,transparent)}
.dsh-drawing-tool-title{color:var(--dsw-alias-label-primary,#19242a);font-weight:700}.dsh-drawing-tool-status{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.dsh-drawing-show{flex:none;margin-left:auto;border:1px solid color-mix(in srgb,#0c5568 35%,var(--dsw-alias-border-l2,#ced8d8));border-radius:999px;background:var(--dsw-alias-bg-base,#fff);color:#0c5568;padding:4px 10px;font:700 11px/1.2 ui-rounded,"PingFang SC",sans-serif;cursor:pointer}.dsh-drawing-show:hover:not(:disabled){border-color:#0c5568;background:#e6f4f3}.dsh-drawing-show:disabled{opacity:.45;cursor:default}
.dsh-drawing-window{position:fixed;z-index:1200;left:50%;top:50%;display:flex;flex-direction:column;width:min(92vw,860px);max-height:88vh;overflow:hidden;transform:translate(calc(-50% + var(--dsh-drawing-offset-x,0px)),calc(-50% + var(--dsh-drawing-offset-y,0px)));color:var(--dsw-alias-label-primary,#19242a);background:var(--dsw-alias-bg-base,#fff);border:1px solid var(--dsw-alias-border-l2,#ced8d8);border-radius:14px;box-shadow:0 18px 48px color-mix(in srgb,var(--dsw-alias-label-primary,#19242a) 20%,transparent);cursor:grab;touch-action:none;animation:dsh-drawing-appear .2s ease-out}.dsh-drawing-window:active{cursor:grabbing}
.dsh-drawing-header{display:flex;align-items:center;justify-content:space-between;min-height:44px;padding:0 12px 0 16px;border-bottom:1px solid var(--dsw-alias-border-l2,#ced8d8);background:var(--dsw-alias-bg-base,#fff)}.dsh-drawing-size{color:var(--dsw-alias-label-secondary,#60666e);font:600 12px/1.2 ui-rounded,"PingFang SC",sans-serif;font-variant-numeric:tabular-nums;letter-spacing:.02em}
.dsh-drawing-close{display:grid;place-items:center;width:28px;height:28px;padding:0;border:0;border-radius:7px;background:transparent;color:var(--dsw-alias-label-secondary,#60666e);font:22px/1 ui-rounded,"PingFang SC",sans-serif;cursor:pointer}.dsh-drawing-close:hover{background:color-mix(in srgb,var(--dsw-alias-label-primary,#19242a) 8%,transparent);color:var(--dsw-alias-label-primary,#19242a)}
.dsh-drawing-stage{min-height:0;overflow:auto;padding:24px;background:var(--dsw-alias-bg-base,#fff)}.dsh-drawing-checkerboard{display:grid;place-items:center;width:max-content;min-width:100%;min-height:260px;background-color:var(--dsw-alias-bg-base,#fff);background-image:linear-gradient(45deg,color-mix(in srgb,var(--dsw-alias-label-primary,#19242a) 7%,transparent) 25%,transparent 25%),linear-gradient(-45deg,color-mix(in srgb,var(--dsw-alias-label-primary,#19242a) 7%,transparent) 25%,transparent 25%),linear-gradient(45deg,transparent 75%,color-mix(in srgb,var(--dsw-alias-label-primary,#19242a) 7%,transparent) 75%),linear-gradient(-45deg,transparent 75%,color-mix(in srgb,var(--dsw-alias-label-primary,#19242a) 7%,transparent) 75%);background-position:0 0,0 12px,12px -12px,-12px 0;background-size:24px 24px;border:1px solid var(--dsw-alias-border-l2,#ced8d8);border-radius:8px}.dsh-drawing-checkerboard canvas{display:block;max-width:min(760px,calc(92vw - 68px));max-height:56vh;object-fit:contain;box-shadow:0 10px 24px color-mix(in srgb,var(--dsw-alias-label-primary,#19242a) 16%,transparent)}@keyframes dsh-drawing-appear{from{opacity:0}to{opacity:1}}@media(max-width:640px){.dsh-drawing-window{width:96vw;max-height:92vh;border-radius:10px}.dsh-drawing-header{padding-left:13px;padding-right:9px}.dsh-drawing-stage{padding:16px 13px}.dsh-drawing-checkerboard canvas{max-width:calc(96vw - 54px)}}@media(prefers-reduced-motion:reduce){.dsh-drawing-window{animation:none}}
`

export function installStyles(): () => void {
  const tag = document.createElement('style')
  tag.dataset.plugin = 'dsh-drawing-plugin'
  tag.textContent = styles
  document.head.appendChild(tag)
  return () => tag.remove()
}
